export const GET_THE_STORIES_DATA = "GET_THE_STORIES_DATA";
export const LOADING = "LOADING";
export const GET_THE_POPULAR_DATA = "GET_THE_POPULAR_DATA";
export const GET_THE_SEARCH_DATA = "GET_THE_SEARCH_DATA";
