export const APIKEY = `7kUyLdjpitBBPhIWN3KTw46JQ09aBQCR`;
export const TRENDING: string[] = [
  "arts",
  "automobiles",
  "books",
  "business",
  "fashion",
  "food",
  "health",
  "home",
  "insider",
  "magazine",
  "movies",
  "nyregion",
  "obituaries",
  "opinion",
  "politics",
  "realestate",
  "science",
  "sports",
  "sundayreview",
  "technology",
  "theater",
  "t-magazine",
  "travel",
  "upshot",
  "us",
  "world",
];
export const TYPES: string[] = ["shared", "emailed", "viewed"];